<?php

namespace GetPageSpeed;

use N98\Magento\Command\AbstractMagentoCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Command\Command;

use Symfony\Component\Console\Input\InputOption;
use N98\Util\Console\Helper\Table\Renderer\RendererFactory;

class MapsGenerateCommand extends AbstractMagentoCommand
{

    protected function configure()
    {
      $this
          ->setName('hypernode:maps-generate')
          ->setDescription('Generate nginx map files for URL redirects')
          ->addOption(
              'store',
              null,
              InputOption::VALUE_OPTIONAL,
              'Store ID (default: all stores)'
          )
          ->addOption(
              'type',
              null,
              InputOption::VALUE_OPTIONAL,
              'Redirect type (301 or 302, default: both)'
          )
      ;
    }

   /**
    * @param \Symfony\Component\Console\Input\InputInterface $input
    * @param \Symfony\Component\Console\Output\OutputInterface $output
    * @return int|void
    */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->detectMagento($output);
        if ($this->initMagento()) {
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
            $connection = $resource->getConnection();
 
            $tableName = $resource->getTableName('url_rewrite');
            
            // Build WHERE clause
            $whereConditions = ['redirect_type IN (301, 302)'];
            
            $storeId = $input->getOption('store');
            if ($storeId !== null) {
                $whereConditions[] = sprintf('store_id = %d', (int)$storeId);
            }
            
            $redirectType = $input->getOption('type');
            if ($redirectType !== null && in_array($redirectType, ['301', '302'])) {
                $whereConditions = [sprintf('redirect_type = %d', (int)$redirectType)];
                if ($storeId !== null) {
                    $whereConditions[] = sprintf('store_id = %d', (int)$storeId);
                }
            }
            
            $where = implode(' AND ', $whereConditions);
            
            $sql = sprintf(
                "SELECT request_path, target_path, redirect_type, store_id FROM `%s` WHERE %s ORDER BY store_id, redirect_type",
                $tableName,
                $where
            );
            
            $redirects = $connection->fetchAll($sql);
            
            if (empty($redirects)) {
                $output->writeln('<info>No redirects found.</info>');
                return Command::SUCCESS;
            }
            
            // Generate nginx map format
            $output->writeln('# Nginx map for URL redirects');
            $output->writeln('# Generated by n98-magerun2 hypernode:maps-generate');
            $output->writeln('');
            
            // Group by redirect type
            $redirectsByType = [];
            foreach ($redirects as $redirect) {
                $type = $redirect['redirect_type'];
                if (!isset($redirectsByType[$type])) {
                    $redirectsByType[$type] = [];
                }
                $redirectsByType[$type][] = $redirect;
            }
            
            foreach ($redirectsByType as $type => $typeRedirects) {
                $output->writeln(sprintf('# %d redirects', $type));
                $output->writeln('map $request_uri $redirect_uri {');
                $output->writeln('    default "";');
                
                foreach ($typeRedirects as $redirect) {
                    $requestPath = '/' . ltrim($redirect['request_path'], '/');
                    $targetPath = '/' . ltrim($redirect['target_path'], '/');
                    
                    // Escape special characters if needed
                    $requestPath = addslashes($requestPath);
                    $targetPath = addslashes($targetPath);
                    
                    $output->writeln(sprintf('    "%s" "%s";', $requestPath, $targetPath));
                }
                
                $output->writeln('}');
                $output->writeln('');
            }

            return Command::SUCCESS;
        } else {
            return Command::FAILURE;
        }
    }
}
